const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const nav=$('#nav'), mobile=$('#mobileMenu');
mobile?.addEventListener('click',()=>nav.classList.toggle('mobile-open'));
$$('nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('mobile-open')));
$$('.dropdown > button').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const menu=btn.nextElementSibling;$$('.dropdown .menu.open').forEach(m=>m!==menu&&m.classList.remove('open'));menu.classList.toggle('open')}));
document.addEventListener('click',()=>$$('.dropdown .menu.open').forEach(m=>m.classList.remove('open')));
$$('[data-form]').forEach(btn=>btn.addEventListener('click',()=>{$('#modalTitle').textContent=btn.dataset.form;$('#modal').classList.add('open')}));
$('#closeModal')?.addEventListener('click',()=>$('#modal').classList.remove('open'));
$('#modal')?.addEventListener('click',e=>{if(e.target.id==='modal')e.target.classList.remove('open')});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#modal')?.classList.remove('open');nav.classList.remove('mobile-open')}});